# ------ Infrastructure settings ------ #
# needed for user creation and alert delivery
db_url: postgresql+asyncpg://postgres:postgres@localhost:5432/postgres

# ---------- Application settings ----- #
# Run 'openssl genrsa -out private.pem 2048' to generate keys
JWT_SECRET: |
    -----BEGIN RSA PRIVATE KEY-----
    ssssssssssssssssssssssssssssss
    ssssssssssssssssssssssssssssss
    ssssssssssssssssssssssssssssss
    ssssssssssssssssssssssssssssss
    -----END RSA PRIVATE KEY-----
# For existing key run 'openssl rsa -in private.pem -pubout -out public.pem'
JWT_PUBLIC: |
    -----BEGIN PUBLIC KEY-----
    ssssssssssssssssssssssssssssss
    ssssssssssssssssssssssssssssss
    sssssssssss
    -----END PUBLIC KEY-----

# ---------- SMTP settings ----- #
smtp_enabled: false
smtp:
    host: smtp.gmail.com
    port: 587
    username: a.a@gmail.com
    password: my_super_password
